// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CsvFileHelper is an autogenerated mock type for the CsvFileHelper type
type CsvFileHelper struct {
	mock.Mock
}

// GetCsvFromFile provides a mock function with given fields: name
func (_m *CsvFileHelper) GetCsvFromFile(name string) ([][]string, error) {
	ret := _m.Called(name)

	var r0 [][]string
	if rf, ok := ret.Get(0).(func(string) [][]string); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
