---
- hosts: all
  tasks:
  - name: create a temporary file for additional data
    file: 
        path: /tmp/tmp-{{Id}}
        state: touch
    become: false

  - name: prepare additional data
    shell: echo {{additionalData}} > /tmp/tmp-{{Id}}
    become: false

  - name: execute post-check operation
    shell: ./swm/upgrade-post-check.sh {{pnfId}} {{oldSwVersion}} {{targetSwVersion}} {{ruleName}} /tmp/tmp-{{Id}}

  - name: remove the temporary file
    file:
        path: /tmp/tmp-{{Id}}
        state: absent
    become: false
