// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kafkaconsumer "oransc.org/nonrtric/dmaapmediatorproducer/internal/kafkaconsumer"
)

// KafkaFactory is an autogenerated mock type for the KafkaFactory type
type KafkaFactory struct {
	mock.Mock
}

// NewKafkaConsumer provides a mock function with given fields: topicID
func (_m KafkaFactory) NewKafkaConsumer(topicID string) (kafkaconsumer.KafkaConsumer, error) {
	ret := _m.Called(topicID)

	var r0 kafkaconsumer.KafkaConsumer
	if rf, ok := ret.Get(0).(func(string) kafkaconsumer.KafkaConsumer); ok {
		r0 = rf(topicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kafkaconsumer.KafkaConsumer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(topicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
