version: '2.1'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}


services:
  db:
    image: mysql/mysql-server:5.6
    container_name: sdnc_db_container
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - MYSQL_ROOT_HOST=%
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  ansible:
    image: onap/sdnc-ansible-server-image:latest
    depends_on :
      - db
    container_name: sdnc_ansible_container
    entrypoint: ["/opt/onap/ccsdk/startAnsibleServer.sh"]
    ports:
      - "8000"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  sdnc:
    image: onap/sdnc-image:latest
    depends_on :
      - db
      - ansible
    container_name: sdnc_controller_container
    entrypoint: ["/opt/onap/sdnc/bin/startODL.sh"]
    ports:
      - "8282:8181"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - ansible:ansiblehost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
    dns:
      - ${DNS_IP_ADDR-10.0.100.1}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    extra_hosts:
        aaf.osaaf.org: 10.12.6.214


  web:
    image: onap/admportal-sdnc-image:latest
    depends_on:
      - db
    container_name: sdnc_portal_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/sdnc/admportal/shell && ./start_portal.sh"
    ports:
      - "8843:8843"
      - "8443:8443"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - CERT_PSWD=onap3.0
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  dgbuilder:
    image: onap/ccsdk-dgbuilder-image:latest
    depends_on:
      - db
    container_name:  sdnc_dgbuilder_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3000:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  ueblistener:
    image: onap/sdnc-ueb-listener-image:latest
    depends_on:
      - db
    container_name:  sdnc_ueblistener_container
    entrypoint: ["/opt/onap/sdnc/ueb-listener/bin/start-ueb-listener.sh" ]
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - PROPERTY_DIR=/opt/onap/sdnc/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  dmaaplistener:
    image: onap/sdnc-dmaap-listener-image:latest
    depends_on:
      - db
    container_name:  sdnc_dmaaplistener_container
    entrypoint: ["/opt/onap/sdnc/dmaap-listener/bin/start-dmaap-listener.sh" ]
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - PROPERTY_DIR=/opt/onap/sdnc/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
