// Code generated by mockery v2.9.3. DO NOT EDIT.

package jobshandler

import (
	mock "github.com/stretchr/testify/mock"
	jobs "oransc.org/nonrtric/dmaapmediatorproducer/internal/jobs"
)

// JobsHandler is an autogenerated mock type for the JobsHandler type
type JobsHandler struct {
	mock.Mock
}

// AddJob provides a mock function with given fields: _a0
func (_m *JobsHandler) AddJobFromRESTCall(_a0 jobs.JobInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(jobs.JobInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteJob provides a mock function with given fields: jobId
func (_m *JobsHandler) DeleteJobFromRESTCall(jobId string) {
	_m.Called(jobId)
}
