 # ========================LICENSE_START=================================
 # Copyright (C) 2021 Nordix Foundation. All rights reserved.
 # ======================================================================
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # ========================LICENSE_END===================================

spring:
  profiles:
    active: prod
server:
   # Configuration of the HTTP/REST server. The parameters are defined and handled by the springboot framework.
   # See springboot documentation.
   port : 8633
   http-port: 8680
   ssl:
      key-store-type: JKS
      key-store: /opt/app/r-app-catalogue/etc/cert/keystore.jks
      key-store-password: r-app-catalogue
      key-password: r-app-catalogue
      key-alias: server-cert
