#  ============LICENSE_START===============================================
#  Copyright (C) 2021 Nordix Foundation. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#


FROM python:3.8-slim-buster

COPY . /usr/src/app/

WORKDIR /usr/src/app

## install curl & ping to help debug
RUN apt update
RUN apt install curl -y
RUN apt-get install iputils-ping -y

RUN pip install -r requirements.txt

CMD [ "python3", "-u", "message_generator.py" ]
