#
# ============LICENSE_START=======================================================
#  Copyright (C) 2022 Nordix Foundation.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum-deployment
  namespace: default
  labels:
    app: chartmuseum
spec:
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      labels:
        app: chartmuseum
        version: v1
    spec:
      containers:
      - name: chartmuseum
        image: chartmuseum/chartmuseum:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: STORAGE
          value: local
        - name: STORAGE_LOCAL_ROOTDIR
          value: /charts
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
        volumeMounts:
        - name: chartdir
          mountPath: /charts
          readOnly: true
      volumes:
      - name: chartdir
        hostPath:
          # Ensure the file directory is created.
           path: /var/chartmuseum/charts
           type: DirectoryOrCreate
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  namespace: default
spec:
  selector:
    app: chartmuseum
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31581
  type: NodePort
