#
# ============LICENSE_START=======================================================
#  Copyright (C) 2022 Nordix Foundation.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapps-istio-mgr-deployment
  namespace: default
  labels:
    app: rapps-istio-mgr
spec:
  selector:
    matchLabels:
      app: rapps-istio-mgr
  template:
    metadata:
      labels:
        app: rapps-istio-mgr
        version: v1
    spec:
      containers:
      - name: rapps-istio-mgr
        image: ktimoney/rapps-istio-mgr
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
      serviceAccountName: helm-app
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rapps-istio-mgr
  namespace: default
spec:
  selector:
    app: rapps-istio-mgr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 31551
  type: NodePort
