openapi: 3.0.0
info:
  title: rAPP Catalogue API
  description: The Non RT-RIC Service Catalogue provides a way for services to register
    themselves for other services to discover.
  version: 1.0.0
servers:
- url: /
paths:
  /services:
    get:
      tags:
      - rAPP Catalogue API
      summary: Services
      operationId: getServices
      responses:
        200:
          description: Services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/service'
      deprecated: false
  /services/{serviceName}:
    get:
      tags:
      - rAPP Catalogue API
      summary: Individual Service
      operationId: getIndividualService
      parameters:
      - name: serviceName
        in: path
        description: serviceName
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      responses:
        200:
          description: EI Job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'
        404:
          description: Service is not found
          content:
            text/plain:
              schema:
                type: string
                example: Service not found
      deprecated: false
    put:
      tags:
      - rAPP Catalogue API
      summary: Create or update a Service
      operationId: putIndividualService
      parameters:
      - name: serviceName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      requestBody:
        description: Service to create/update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputService'
        required: true
      responses:
        200:
          description: Service updated
        201:
          description: Service created
        400:
          description: Provided service is not correct
          content:
            text/plain:
              schema:
                type: string
                example: 'Service is missing required property: version'
      deprecated: false
    delete:
      tags:
      - rAPP Catalogue API
      summary: Remove a Service from the catalogue
      operationId: deleteIndividualService
      parameters:
      - name: serviceName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      responses:
        204:
          description: Service deleted
      deprecated: false
components:
  schemas:
    inputService:
      title: inputService
      required:
      - version
      type: object
      properties:
        version:
          type: string
          description: Version of the Service
          example: 1.0.0
        display_name:
          type: string
          description: Display name for the Service
          example: Drone Identifier
        description:
          type: string
          description: Description of the Service
          example: Detects if a UE is a drone
      description: A Service to register
    service:
      title: service
      required:
      - name
      - version
      type: object
      properties:
        name:
          type: string
          description: Unique identifier of the Service
          example: DroneIdentifier
        version:
          type: string
          description: Version of the Service
          example: 1.0.0
        display_name:
          type: string
          description: Display name for the Service
          example: Drone Identifier
        description:
          type: string
          description: Description of the Service
          example: Detects if a UE is a drone
      description: A Service
